# Generated by Django 3.2.8 on 2022-03-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='part',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videos',
            name='seasons',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
