# Generated by Django 3.2.12 on 2022-04-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_balancehistory_paymentsystem_topupbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='cost',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='topupbalance',
            name='cost',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
